# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe75efd626c1072fd100cbd16664aec7ce8ade8838fd886940d10be071ec7e193b275ae6d860dc916ad5dead1be4566bd6bc571c30cc6985562fa68624adf778

test:
  secret_key_base: 1224d6085af20ce49243dd77991f707a0e60c49904603e7db6f3eb564810e6b7bc48946fe7654ad5275808c5f95704845e696bc4d94bbf971d21c313d0c68bbc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
